name: ci-link-check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lychee:
    name: lychee link checker
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Lychee Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: --config .lycheecrc --no-progress **/*.md
          fail: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
